import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {

  const [url, setUrl] = useState('')
  return (
    <div className={styles.container}>
      <Head>
        <title>Igor Bayerl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <input 
          className={styles.card}
          type='url'
          value={url}
          onChange={(e) => setUrl(e.target.value)}  
        />

        <div className={styles.grid}>
          <a 
            className={styles.card}
            href={`/api/ytdl?url=${url}`}
          >
            <p>Download &rarr;</p>
          </a>
        </div>
      </main>

      
    </div>
  )
}
